export enum ActionType {
  SET_ATTEMPS = "set-attemps",
  SET_ELAPSED_TIME = "set-elapsed_time",
  SET_INTERVAL_ID = "set-interval-id",
  SET_RESET = "set-reset",
  SET_WIN = "set-win",
  RESET_APP_STAT = "reset-app-stat",
  SET_GAME_RESULT = "set-game-result",
  SET_NAME = "set-name",
  SAVE_PHRASE = "save-phrase",
  SAVE_SELECTED_LETTERS = "save-selected-letters",
  SAVE_RIGHT_LETTERS = "save-right-letters",
  RESET_APP_USER = "reset-app-user",
  RESET_APP_GAME = "reset-app-game",
}
